/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Website = {
  _id: string;
  _type: "website";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  frontPage?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  mainMenu?: Array<({
    _key: string;
  } & InternalLink) | ({
    _key: string;
  } & ExternalLink)>;
  contactInfo?: {
    orgName?: string;
    orgNr?: string;
    address?: string;
    postalCode?: string;
    city?: string;
  };
};

export type YouTubeVideo = {
  _type: "youTubeVideo";
  url?: string;
};

export type SearchBox = {
  _type: "searchBox";
  title?: string;
};

export type ProductListSelection = {
  _type: "productListSelection";
  products?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "product";
  }>;
};

export type ProductListAll = {
  _type: "productListAll";
  title?: string;
};

export type ImageGallery = {
  _type: "imageGallery";
  title?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
    _key: string;
  }>;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6";
    listItem?: "bullet" | "number";
    markDefs?: Array<({
      _key: string;
    } & InternalLink) | ({
      _key: string;
    } & ExternalLink)>;
    level?: number;
    _type: "extendedBlock";
    _key: string;
  }>;
  aspectRatio?: "IMAGE_ASPECT_RATIO_1_1" | "IMAGE_ASPECT_RATIO_4_3" | "IMAGE_ASPECT_RATIO_16_9";
};

export type FeaturedQuote = {
  _type: "featuredQuote";
  name?: string;
  person?: string;
  quote?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
  };
};

export type ExtendedBlock = {
  _type: "extendedBlock";
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6";
  listItem?: "bullet" | "number";
  markDefs?: Array<({
    _key: string;
  } & InternalLink) | ({
    _key: string;
  } & ExternalLink)>;
  level?: number;
};

export type ArticleListSelection = {
  _type: "articleListSelection";
  title?: string;
  articles?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "article";
  }>;
};

export type ArticleListFromFeed = {
  _type: "articleListFromFeed";
  title?: string;
  articleFeed?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "articleFeed";
  };
};

export type ArticleFeed = {
  _id: string;
  _type: "articleFeed";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
};

export type ArticleListAll = {
  _type: "articleListAll";
  title?: string;
};

export type RichPortableText = Array<({
  _key: string;
} & ArticleListAll) | ({
  _key: string;
} & ArticleListFromFeed) | ({
  _key: string;
} & ArticleListSelection) | ({
  _key: string;
} & ExtendedBlock) | ({
  _key: string;
} & FeaturedQuote) | ({
  _key: string;
} & ImageGallery) | ({
  _key: string;
} & ProductListAll) | ({
  _key: string;
} & ProductListSelection) | ({
  _key: string;
} & SearchBox) | ({
  _key: string;
} & YouTubeVideo)>;

export type InternalLink = {
  _type: "internalLink";
  reference?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "article";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  } | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  tagline?: string;
  description?: Array<{
    _key: string;
  } & ExtendedBlock>;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
  };
  tag?: string;
  content?: RichPortableText;
  supplementaryContent?: RichPortableText;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  headers?: Array<({
    _key: string;
  } & ContentHeader) | ({
    _key: string;
  } & ImageHeader)>;
  content?: RichPortableText;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  heading?: string;
  lead?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
  };
  content?: RichPortableText;
  articleFeeds?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "articleFeed";
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type ImageHeader = {
  _type: "imageHeader";
  heading?: string;
  lead?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
  };
  style?: "STYLE_MEDIA_FOCUS" | "STYLE_TEXT_FOCUS";
};

export type ImageWeb = {
  _type: "imageWeb";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  credit?: string;
  caption?: string;
};

export type ExternalLink = {
  _type: "externalLink";
  text?: string;
  url?: string;
};

export type ContentHeader = {
  _type: "contentHeader";
  heading?: string;
  lead?: string;
  shortcuts?: Array<({
    _key: string;
  } & InternalLink) | ({
    _key: string;
  } & ExternalLink)>;
};

export type BasicPortableText = Array<{
  _key: string;
} & ExtendedBlock>;
export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: groq/get-article-list-all-page.ts
// Variable: getArticleListAllPage
export type GetArticleListAllPageResult = Array<SanityArticleInCard>;

// Source: groq/get-article-list-from-feed-page.ts
// Variable: getArticleListFromFeedPage
export type GetArticleListFromFeedPageResult = Array<SanityArticleInCard>;

// Source: groq/get-article-page.ts
// Variable: getArticlePageBySlugQuery
export type GetArticlePageBySlugQueryResult = {
  website: SanityWebsite | null;
  article: SanityArticle | null;
};

// Source: groq/get-page.ts
// Variable: getPageBySlugQuery
export type GetPageBySlugQueryResult = {
  website: SanityWebsite | null;
  page: SanityPage | null;
};

// Source: groq/get-product-page.ts
// Variable: getProductPageBySlugQuery
export type GetProductPageBySlugQueryResult = {
  website: SanityWebsite | null;
  product: SanityProduct | null;
};



export type SanityArticleInCard = {
  _id: string;
  _type: "article";
  slug: Slug | null;
  heading: string | null;
  lead: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    altText?: string;
    credit?: string;
    caption?: string;
    _type: "imageWeb";
  } | null;
  _ts: "SanityArticleInCard";
};


export type SanityExternalLink = {
      _type: "externalLink";
      text: string | null;
      url: string | null;
      _ts: "SanityExternalLink";
    };


export type SanityInternalLinkarticle = {
        _id: string;
        _type: "article";
        slug: Slug | null;
        title: string | null;
        _ts: "SanityInternalLinkarticle";
      };


export type SanityInternalLinkpage = {
        _id: string;
        _type: "page";
        slug: Slug | null;
        title: string | null;
        _ts: "SanityInternalLinkpage";
      };


export type SanityInternalLinkproduct = {
        _id: string;
        _type: "product";
        slug: Slug | null;
        title: null | string;
        _ts: "SanityInternalLinkproduct";
      };


export type SanityWebsite = {
    _id: string;
    title: string | null;
    frontPage: {
      title: string | null;
      slug: Slug | null;
    } | null;
    mainMenu: Array<SanityExternalLink | {
      reference: SanityInternalLinkarticle | SanityInternalLinkpage | SanityInternalLinkproduct | null;
    }> | null;
    contactInfo: {
      orgName: string | null;
      orgNr: string | null;
      address: string | null;
      postalCode: string | null;
      city: string | null;
    } | null;
    _ts: "SanityWebsite";
  };


export type SanityImageWeb = {
      _type: "imageWeb";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      altText: string | null;
      credit: string | null;
      caption: string | null;
      _ts: "SanityImageWeb";
    };


export type SanitySearchBox = {
      _key: string;
      _type: "searchBox";
      title: string | null;
      _ts: "SanitySearchBox";
    };


export type SanityArticleListAll = {
      _type: "articleListAll";
      title: string | null;
      firstPage: {
        articles: Array<SanityArticleInCard>;
        totalCount: 0 | unknown;
      };
      _ts: "SanityArticleListAll";
    };


export type SanityArticleFeed = {
        _id: string;
        name: string | null;
        _ts: "SanityArticleFeed";
      };


export type SanityArticleListFromFeed = {
      _type: "articleListFromFeed";
      title: string | null;
      articleFeed: SanityArticleFeed | null;
      firstPage: {
        articles: Array<SanityArticleInCard>;
        totalCount: 0 | unknown;
      };
      _ts: "SanityArticleListFromFeed";
    };


export type SanityArticleListSelection = {
      _type: "articleListSelection";
      title: string | null;
      articles: Array<SanityArticleInCard> | null;
      _ts: "SanityArticleListSelection";
    };


export type SanityExtendedBlock = {
      _type: "extendedBlock";
      children: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }> | null;
      style: "h2" | "h3" | "h4" | "h5" | "h6" | "normal" | null;
      listItem: "bullet" | "number" | null;
      markDefs: Array<SanityExternalLink | {
        _key: string;
        reference: SanityInternalLinkarticle | SanityInternalLinkpage | SanityInternalLinkproduct | null;
      }> | null;
      level: number | null;
      _ts: "SanityExtendedBlock";
    };


export type SanityFeaturedQuote = {
      _type: "featuredQuote";
      name: string | null;
      person: string | null;
      quote: string | null;
      image: SanityImageWeb | null;
      _ts: "SanityFeaturedQuote";
    };


export type SanityImageGallery = {
      _type: "imageGallery";
      title: string | null;
      images: Array<SanityImageWeb> | null;
      text: Array<SanityExtendedBlock> | null;
      aspectRatio: "IMAGE_ASPECT_RATIO_1_1" | "IMAGE_ASPECT_RATIO_16_9" | "IMAGE_ASPECT_RATIO_4_3" | null;
      _ts: "SanityImageGallery";
    };


export type SanityProductInCard = {
        _id: string;
        _type: "product";
        name: string | null;
        slug: Slug | null;
        tagline: string | null;
        mainImage: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          altText?: string;
          credit?: string;
          caption?: string;
          _type: "imageWeb";
        } | null;
        tag: string | null;
        _ts: "SanityProductInCard";
      };


export type SanityProductListAll = {
      _type: "productListAll";
      title: string | null;
      products: Array<SanityProductInCard>;
      _ts: "SanityProductListAll";
    };


export type SanityProductListSelection = {
      _type: "productListSelection";
      products: Array<SanityProductInCard> | null;
      _ts: "SanityProductListSelection";
    };


export type SanityYouTubeVideo = {
      _type: "youTubeVideo";
      url: string | null;
      _ts: "SanityYouTubeVideo";
    };


export type SanityArticle = {
    _id: string;
    _type: "article";
    title: string | null;
    slug: Slug | null;
    heading: string | null;
    lead: string | null;
    image: SanityImageWeb | null;
    content: Array<SanitySearchBox | SanityArticleListAll | SanityArticleListFromFeed | SanityArticleListSelection | SanityExtendedBlock | SanityFeaturedQuote | SanityImageGallery | SanityProductListAll | SanityProductListSelection | SanityYouTubeVideo> | null;
    articleFeeds: Array<SanityArticleFeed> | null;
    _ts: "SanityArticle";
  };


export type SanityContentHeader = {
      _type: "contentHeader";
      heading: string | null;
      lead: string | null;
      shortcuts: Array<SanityExternalLink | {
        reference: SanityInternalLinkarticle | SanityInternalLinkpage | SanityInternalLinkproduct | null;
      }> | null;
      _ts: "SanityContentHeader";
    };


export type SanityImageHeader = {
      _type: "imageHeader";
      heading: string | null;
      lead: string | null;
      image: SanityImageWeb | null;
      style: "STYLE_MEDIA_FOCUS" | "STYLE_TEXT_FOCUS" | null;
      _ts: "SanityImageHeader";
    };


export type SanityPage = {
    _id: string;
    title: string | null;
    slug: Slug | null;
    headers: Array<SanityContentHeader | SanityImageHeader> | null;
    content: Array<SanitySearchBox | SanityArticleListAll | SanityArticleListFromFeed | SanityArticleListSelection | SanityExtendedBlock | SanityFeaturedQuote | SanityImageGallery | SanityProductListAll | SanityProductListSelection | SanityYouTubeVideo> | null;
    _ts: "SanityPage";
  };


export type SanityProduct = {
    _id: string;
    _type: "product";
    name: string | null;
    slug: Slug | null;
    tagline: string | null;
    description: Array<SanityExtendedBlock> | null;
    mainImage: SanityImageWeb | null;
    tag: string | null;
    content: Array<SanitySearchBox | SanityArticleListAll | SanityArticleListFromFeed | SanityArticleListSelection | SanityExtendedBlock | SanityFeaturedQuote | SanityImageGallery | SanityProductListAll | SanityProductListSelection | SanityYouTubeVideo> | null;
    supplementaryContent: Array<SanitySearchBox | SanityArticleListAll | SanityArticleListFromFeed | SanityArticleListSelection | SanityExtendedBlock | SanityFeaturedQuote | SanityImageGallery | SanityProductListAll | SanityProductListSelection | SanityYouTubeVideo> | null;
    _ts: "SanityProduct";
  };
